### ISSUE TITLE
Setting time zone with inittimezone not working

### ISSUE THREAD

**Issue by jonahaag** [Simulation-Software-Engineering/cmake-exercise#1]
I am still prompted to input geographic information, e.g. when trying to install Boost via `apt install -y libboost-all-dev`, even after copying the `inittimezone` to `/usr/local/bin/inittimezone`. 
I confirmed that copied file is there and tried the package installation manually in interactive mode. Running `chmod +x inittimezone` also does not seem to change anything for me.

Any suggestions to get it to work as intended?

**Comment by uekerman** [comment]
@Ovakefali13 had a similar issue. Copying the content of the script `inittimezone` directly into `Dockerfile` did the job for him.
@Ovakefali13: Could you maybe post the corresponding lines of your `Dockerfile` here?

**Comment by jonahaag** [comment]
```
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```
seems to do the trick based on [this](https://dev.to/setevoy/docker-configure-tzdata-and-timezone-during-build-20bk). Looking at the content of `inittimezone` confirms this.

**Comment by cheriimoya** [comment]
did you run the script after `COPY`ing it?
it is not executed automatically, you'll have to run it yourself

```Dockerfile
COPY inittimezone /usr/local/bin/inittimezone
RUN inittimezone
```

**Comment by jonahaag** [comment]
Well, that obviously explains things 😄 🤦‍♂️   Thanks for the hint!

**Comment by uekerman** [comment]
Of course, this makes sense :grin: Thanks for pointing out.
I added this to the exercise sheet in https://github.com/Simulation-Software-Engineering/Lecture-Material/commit/5acdb2cc37d8bfdd8bc1612169cb585d06e6db60 .

**Comment by Ovakefali13** [comment]
> ```
> ENV TZ=Europe/Berlin
> RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
> ```
> 
> seems to do the trick based on [this](https://dev.to/setevoy/docker-configure-tzdata-and-timezone-during-build-20bk). Looking at the content of `inittimezone` confirms this.

I just got the notification of this issue and it is closed already, but I did use this method as well, thanks @jonahaag for sharing ;-)
